# ===================================================================
# 1. PARÂMETROS DE DADOS E VALIDAÇÃO
# ===================================================================
dataset:
  raw_file_name: "Obfuscated-MalMem2022.csv"
  random_seed: 117

cross_validation:
  n_splits: 10 
  test_size: 0.2
  
# ===================================================================
# 2. PARÂMETROS DE TREINAMENTO
# ===================================================================
training:
  optimizer: 'Adam'
  learning_rate: 0.0001
  weight_decay: 0.0001
  batch_size: 64
  epochs: 500
  early_stopping_patience: 25

# ===================================================================
# 3. ARQUITETURAS DOS MODELOS
# ===================================================================
architectures:

  cnn:
    dropout_rate: 0.25
    cnn_channels: [3, 16, 32,64,128] # (Entrada, Conv1, Conv2, Conv3, Conv4)
    kernel_size: 3

  DeepNN_MLP: 
    dropout_rate: 0.5 
    hidden_layers: [512, 256, 128, 64] 

  Autoencoder_SAE: 
    pretrain_epochs: 50
    

  DeepNN_SAE_Classifier:
    dropout_rate: 0.5
  